[[libboxer]]
arch = "aarch64"
git-tree-sha1 = "31c0b3cfd6de2497b1dcb9aff9794fce7150a4ee"
libc = "glibc"
os = "linux"

    [[libboxer.download]]
    sha256 = "4230c6d004fb1fd0cde3432035e532db907023332eb514ac3ca9c9072ab335d5"
    url = "https://github.com/JuliaBinaryWrappers/libboxer_jll.jl/releases/download/libboxer-v0.4.0+0/libboxer.v0.4.0.aarch64-linux-gnu.tar.gz"
[[libboxer]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f2122c7930af891679bdb859e1d6cfa80a8fe798"
libc = "glibc"
os = "linux"

    [[libboxer.download]]
    sha256 = "fa1811110cd8469c51117c82b2b32575792ff412792ce1c7df5b78aaeb992b69"
    url = "https://github.com/JuliaBinaryWrappers/libboxer_jll.jl/releases/download/libboxer-v0.4.0+0/libboxer.v0.4.0.armv6l-linux-gnueabihf.tar.gz"
[[libboxer]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "279b6ab601ad4a06a7182b8f292c65f4ff6fb985"
libc = "glibc"
os = "linux"

    [[libboxer.download]]
    sha256 = "c3a6061c72fe20f69cefc1a94f8a0f23879c4fa05959294e2ce0e1afdb574398"
    url = "https://github.com/JuliaBinaryWrappers/libboxer_jll.jl/releases/download/libboxer-v0.4.0+0/libboxer.v0.4.0.armv7l-linux-gnueabihf.tar.gz"
[[libboxer]]
arch = "i686"
git-tree-sha1 = "b1b326f5e3912fde5b24119ae37d14f1c1d6ebbf"
libc = "glibc"
os = "linux"

    [[libboxer.download]]
    sha256 = "8715b8971f93aa6a5a807a102905e83d55a02fbe2c445ab6c6ed686b74760b36"
    url = "https://github.com/JuliaBinaryWrappers/libboxer_jll.jl/releases/download/libboxer-v0.4.0+0/libboxer.v0.4.0.i686-linux-gnu.tar.gz"
[[libboxer]]
arch = "powerpc64le"
git-tree-sha1 = "4f2ac43629b07f17c8dfd309012694ebf6586f5f"
libc = "glibc"
os = "linux"

    [[libboxer.download]]
    sha256 = "a753fc0163667520bc00b91e4f0065610fc128532258bc7317927f76f4789436"
    url = "https://github.com/JuliaBinaryWrappers/libboxer_jll.jl/releases/download/libboxer-v0.4.0+0/libboxer.v0.4.0.powerpc64le-linux-gnu.tar.gz"
[[libboxer]]
arch = "x86_64"
git-tree-sha1 = "77255d580d2a5c9c5e4e74466e399d110103e9fd"
libc = "glibc"
os = "linux"

    [[libboxer.download]]
    sha256 = "61386627858fc546f2de5af15db5a6f640cf353bb8ad66963d9806bc5434ae73"
    url = "https://github.com/JuliaBinaryWrappers/libboxer_jll.jl/releases/download/libboxer-v0.4.0+0/libboxer.v0.4.0.x86_64-linux-gnu.tar.gz"
[[libboxer]]
arch = "x86_64"
git-tree-sha1 = "1a919113a9519eac575cd22dc32b4cfe7462ba21"
os = "windows"

    [[libboxer.download]]
    sha256 = "6cd81d89fe0704ac436f180599f6fc411801b26dcd04e5c580d0218a9c28aac2"
    url = "https://github.com/JuliaBinaryWrappers/libboxer_jll.jl/releases/download/libboxer-v0.4.0+0/libboxer.v0.4.0.x86_64-w64-mingw32.tar.gz"
