# Autogenerated wrapper script for libboxer_jll for x86_64-w64-mingw32
export boxer_h, libBoxer

JLLWrappers.@generate_wrapper_header("libboxer")
JLLWrappers.@declare_file_product(boxer_h)
JLLWrappers.@declare_library_product(libBoxer, "libBoxer.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        boxer_h,
        "include\\boxer.h",
    )

    JLLWrappers.@init_library_product(
        libBoxer,
        "bin\\libBoxer.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
